# Generated by ChatGPT on 2025-09-27
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(choices=[("image", "Image"), ("video", "Video"), ("ad", "Ad")], default="image", max_length=8),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("sale_price", models.PositiveIntegerField(blank=True, null=True)),
                ("cta", models.CharField(blank=True, max_length=60)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("media_src", models.URLField(blank=True)),
                ("poster", models.URLField(blank=True)),
                ("href", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="categories.category"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="categories.subcategory"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="products.product"),
                ),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "media_type",
                    models.CharField(choices=[("image", "Image"), ("video", "Video")], default="image", max_length=8),
                ),
                ("file", models.FileField(blank=True, upload_to="products/media/")),
                ("external_url", models.URLField(blank=True)),
                ("poster", models.FileField(blank=True, upload_to="products/posters/")),
                ("alt_text", models.CharField(blank=True, max_length=120)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="products.product"),
                ),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=40)),
                ("color_swatch", models.CharField(blank=True, max_length=32)),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("price_override", models.PositiveIntegerField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.product"),
                ),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="ProductMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="metrics", to="products.product"),
                ),
            ],
        ),
    ]
