# Generated by Django 6.0.1 on 2026-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cta_ro',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cta_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ro',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_ro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_ro',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='alt_text_ro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='caption_ro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_ro',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_ro',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_ru',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
