# Generated by ChatGPT on 2025-09-27
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="auth.user"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("paid", "Paid"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("delivery_fee", models.PositiveIntegerField(default=0)),
                ("items_total", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                (
                    "payment_method",
                    models.CharField(choices=[("transfer", "Transfer"), ("cash", "Cash")], max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_address",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orders.address"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auth.user"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.PositiveIntegerField()),
                ("line_total", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.product"),
                ),
                (
                    "variant",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="products.productvariant"),
                ),
            ],
        ),
    ]
