# Generated by Django 6.0.1 on 2026-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'label')},
        ),
        migrations.AddField(
            model_name='category',
            name='description_ro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='label_ro',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='label_ru',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='label_ro',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='label_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'label'), ('category', 'label_ro'), ('category', 'label_ru')},
        ),
    ]
